# This is a basic workflow to help you get started with Actions

name: Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup MSBuild
        uses: microsoft/Setup-MSBuild@v1

      # Runs a set of commands using the runners shell
      #- name: Setup NuGet
      #  uses: NuGet/setup-nuget@v1.0.2
        
      #- name: Restore NuGet Packages 
      #  run: nuget restore MC-HEXColor-Gadient-Generator.sln
        
      - name: Build
        run: msbuild /p:Configuration=Release /Restore:True MC-HEXColor-Gadient-Generator.sln
      
      - name: Package and generate hashes
        shell: pwsh
        run: ./action.ps1
        
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ env.TagName }}
          title: ${{ env.ReleaseName }}
          files: |
            sums.txt
            ${{ env.ReleaseFileName }}
